### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by p9g** [HL7/cql#1]
Many tables that look ok on github (.adoc) do not render correctly on HL7 site (.html).  For example, Table 2-B.
Compare 
https://github.com/HL7/cql/blob/master/spec/2018May/02-authorsguide.adoc#parameters
and
https://cql.hl7.org/2018May/02-authorsguide.html#parameters

**Comment by brynrhodes** [comment]
This issue was addressed as part of reconciling ballot comments and the published spec now renders tables correctly:

https://cql.hl7.org/02-authorsguide.html#parameters
