### ISSUE TITLE
Fix Test ExistsListNull

### ISSUE THREAD

**Issue by alexanderkiel** [HL7/cql#52]
According to the thread [CQL Execution](https://chat.fhir.org/#narrow/stream/179220-cql/topic/CQL.20Execution) the semantics of [exists](https://cql.hl7.org/09-b-cqlreference.html#exists) have changed. That change should be reflected in tests, because there is a test called [ExistsListNull](https://github.com/HL7/cql/blob/3ea0bcb7a28578118982b0058324c41cc0608f6f/tests/cql/CqlListOperatorsTest.xml#L186). Happy to create a PR, if I'm right here.

**Comment by cmoesel** [comment]
I just confirmed on the Zulip thread, but will confirm here as well.  The semantics of `exist` changed in CQL 1.3.0 ([change log](https://cql.hl7.org/v1.3-changelog.html)) in response to [comment 1435](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1435).

Thanks for pointing out the invalid test.  Yikes!

**Comment by alexanderkiel** [comment]
Should I file a PR?

**Comment by brynrhodes** [comment]
I've submitted STU comment [1876](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=1876) to address this.

Feel free to submit a PR and we will include it in a planned errata publication, pending approval of the above STU comment.

**Comment by brynrhodes** [comment]
Addressed
