### ISSUE TITLE
Clarify subtype behavior for `Is` operator in Appendix B

### ISSUE THREAD

**Issue by suyashkumar** [HL7/cql#84]
As discussed in this [FHIR chat](https://chat.fhir.org/#narrow/stream/179220-cql/topic/Type.20Testing.20.28Derived.20System.20Types.29), it is an important semantic that `Is` also returns true for a subtype relationship where `T' is T` is true if `T'` is derived from T. This is mentioned in the [developer guide](https://cql.hl7.org/03-developersguide.html#type-testing), but not in the [system operator definition](https://cql.hl7.org/09-b-cqlreference.html#is). This ticket is for adding a note about this behavior to the system operator definition in particular.

Thanks!

**Comment by brynrhodes** [comment]
Hi @suyashkumar ! Thank you for submitting this issue. Since this is a change to the CQL specification though, it needs to be submitted as a JIRA tracker. I've submitted it as a Technical Correction here: https://jira.hl7.org/browse/FHIR-46053

Closing this issue as it is is now tracked in JIRA.
